ALTER TABLE match ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'csv_historique';
ALTER TABLE match ADD COLUMN IF NOT EXISTS id_externe INTEGER;
ALTER TABLE match ADD COLUMN IF NOT EXISTS statut VARCHAR(20) DEFAULT 'FINISHED';

CREATE UNIQUE INDEX IF NOT EXISTS idx_match_id_externe
    ON match (id_externe) WHERE id_externe IS NOT NULL;