DROP TABLE IF EXISTS ancien_nom;
DROP TABLE IF EXISTS tirs_au_but;
DROP TABLE IF EXISTS but;
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS tournoi;
DROP TABLE IF EXISTS equipe;

CREATE TABLE equipe (
    id_equipe   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tournoi (
    id_tournoi  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom         VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE match (
    id_match             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_match           DATE         NOT NULL,
    id_equipe_domicile   INTEGER      NOT NULL REFERENCES equipe(id_equipe),
    id_equipe_exterieur  INTEGER      NOT NULL REFERENCES equipe(id_equipe),
    score_domicile       SMALLINT     NOT NULL CHECK (score_domicile >= 0),
    score_exterieur      SMALLINT     NOT NULL CHECK (score_exterieur >= 0),
    id_tournoi           INTEGER      NOT NULL REFERENCES tournoi(id_tournoi),
    ville                VARCHAR(100) NOT NULL,
    pays                 VARCHAR(100) NOT NULL,
    terrain_neutre       BOOLEAN      NOT NULL,
    CONSTRAINT ck_equipes_differentes
        CHECK (id_equipe_domicile <> id_equipe_exterieur)
);

CREATE TABLE but (
    id_but               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_match             INTEGER      NOT NULL REFERENCES match(id_match) ON DELETE CASCADE,
    id_equipe            INTEGER      NOT NULL REFERENCES equipe(id_equipe),
    buteur               VARCHAR(150),
    minute               SMALLINT     CHECK (minute BETWEEN 0 AND 130),
    but_contre_son_camp  BOOLEAN      NOT NULL DEFAULT FALSE,
    penalty              BOOLEAN      NOT NULL DEFAULT FALSE
);

CREATE TABLE tirs_au_but (
    id_match                  INTEGER PRIMARY KEY REFERENCES match(id_match) ON DELETE CASCADE,
    id_equipe_vainqueur       INTEGER NOT NULL REFERENCES equipe(id_equipe),
    id_equipe_premier_tireur  INTEGER REFERENCES equipe(id_equipe)
);

CREATE TABLE ancien_nom (
    id_ancien_nom  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipe      INTEGER      NOT NULL REFERENCES equipe(id_equipe),
    nom_ancien     VARCHAR(100) NOT NULL,
    date_debut     DATE         NOT NULL,
    date_fin       DATE         NOT NULL,
    CONSTRAINT ck_dates_ancien_nom CHECK (date_fin >= date_debut)
);